apiVersion: v1
kind: Service
metadata:
  name: student-management-app-service
spec:
  type: NodePort
  selector:
    app: student-management-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
