name: Spring Boot CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1 — Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2 — Install Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3 — Maven Build
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Step 4 — Login to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5 — Build Docker Image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/student-management-app:latest .

      # Step 6 — Push Docker Image
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/student-management-app:latest
