name: Spring Boot CI/CD + Kubernetes Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1 — Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2 — Install Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3 — Maven Build
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Step 4 — Login to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5 — Build Docker Image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/student-management-app:latest .

      # Step 6 — Push Docker Image
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/student-management-app:latest

      # -------------------------------
      # KUBERNETES DEPLOYMENT SECTION
      # -------------------------------

      # Step 7 — Install kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      # Step 8 — Load kubeconfig from GitHub Secret
      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      # Step 9 — Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s-deployment.yaml
          kubectl apply -f k8s-service.yaml

      # Step 10 — Verify Deployment
      - name: Check Deployment Status
        run: |
          kubectl rollout status deployment/student-deployment
          kubectl get pods -o wide
